###############################################################################
# Necessary Check
###############################################################################
KBUILD_CONNFEM_ENABLED = yes

ifeq ($(KBUILD_CONNFEM_ENABLED), yes)
    KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
    include $(KO_CODE_PATH)/Kbuild.main
endif

