# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

$(info $(DEVICE_MODULES_PATH))
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/smi/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/
ccflags-$(CONFIG_MTK_IOMMU_V2) += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(KO_PATH)/../camsys/isp8/cam

NOTDIR_DEVICE_MODULES_PATH = $(notdir $(DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
#$(info pda sort=$(sort 6.6 $(KERNEL_VERSION)))
#$(info pda word=$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DDMA_BUF_UNLOCKED_API
endif

# driver module
#obj-m := camera_pda_dummy.o
# rodin batch4-4: 只编 pda_drv_mt6899。三件共享同一个 isp_8/camera_pda.o 会让
# kbuild 传 -D__KBUILD_MODNAME=kmod_pda_drv_mt6991:pda_drv_mt6899:...，6.18 的
# MODULE_DEVICE_TABLE 把它 __PASTE 进标识符 ⇒ 编译失败；且设备只出货
# pda_drv_mt6899.ko（无 mt6991/dummy）。
ifneq ($(wildcard $(KO_PATH)/isp_8/pda_mt6899.c),)
obj-$(CONFIG_MTK_CAMERA_ISP_PDA_SUPPORT) += pda_drv_mt6899.o
endif

pda_drv_mt6991-objs := isp_8/camera_pda.o isp_8/pda_mt6991.o
pda_drv_mt6899-objs := isp_8/camera_pda.o isp_8/pda_mt6899.o
pda_drv_dummy-objs := isp_8/camera_pda.o isp_8/pda_dummy.o