# Copyright Statement:
#
# This software/firmware and related documentation ("MediaTek Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to MediaTek Inc. and/or its licensors.
# Without the prior written permission of MediaTek inc. and/or its licensors,
# any reproduction, modification, use or disclosure of MediaTek Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.
#
# MediaTek Inc. (C) 2017. All rights reserved.
#
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
# RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
# AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER\'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
# SOFTWARE RELEASES MADE TO RECEIVER\'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER\'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK\'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
# AT MEDIATEK\'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#
# The following software/firmware and/or related documentation ("MediaTek Software")
# have been modified by MediaTek Inc. All revisions are subject to any receiver\'s
# applicable license agreements with MediaTek Inc.
#

MTK_TOP = $(srctree)/drivers/misc/mediatek/

# rodin 6.9：原 `ifeq ($(CONFIG_MTK_HBT),m)` 在 =y 时不成立 ⇒ -DCONFIG_MTK_HBT
# 静默消失 ⇒ 源码里各 #ifdef CONFIG_MTK_HBT 分支被剪掉（编译期无感知）。
ifneq ($(filter y m,$(CONFIG_MTK_HBT)),)
ccflags-y += -DCONFIG_MTK_HBT
subdir-ccflags-y += -DCONFIG_MTK_HBT
endif

ccflags-y += \
	     -I$(srctree)/include/ \
	     -I$(MTK_TOP)/include/ \

# rodin 6.9：原为无条件 `obj-m += hbt.o`（设备构建层保证该件必编）。
# 内建 =y 需要语义门，否则 obj-m 让 kbuild 仍按模块处理 ⇒ 不进 vmlinux。
# 设备 hbt.ko 真实发货（hbt_driver/src/hbt.c 507 行真身；同树 hbt_driver_cus/
# 是 79 行残桩且被其 Android.mk 的反向守卫排除），故 CONFIG_MTK_HBT=y 时内建。
obj-$(CONFIG_MTK_HBT) += hbt.o
hbt-y += src/hbt.o

# rodin 6.9：原 KO_CODE_PATH/REL_PREBUILT_O_PATH 依赖 scripts/get_rel_path.sh ——
# 本树无该脚本（MTK Android 构建层专有），$(shell) 每次解析都往 stderr 打
# "No such file or directory"，且两个变量全树无消费者（hbt 真实现是 src/hbt.c，
# 不是 .o_shipped）⇒ 删掉这两行死代码。
