ifneq (,$(filter $(CONFIG_MTK_MET),y m))
ORIGIN_SRC := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
override src := $(ORIGIN_SRC)/../..

include $(src)/Kbuild

override src := $(ORIGIN_SRC)

ifneq ("$(wildcard $(MET_ROOT_DIR)/../met_drv_secure_v3)","")
	ccflags-y += -DMET_PLF_EXIST
endif

obj-$(CONFIG_MTK_MET) := met_scmi_api.o
met_scmi_api-y := met_scmi_api.o
# rodin: 批4-5 =y 内建補 -I（=m 时这两条由 common/Kbuild 提供）
ccflags-y += -I$(MET_ROOT_DIR)/met_api
ccflags-y += -I$(MET_ROOT_DIR)/common # rodin: 批4-5 =y 内建（default/ 布局的 -y 是 stub 路径）
endif
